-- CreateTable
CREATE TABLE "toDos" (
    "id" SERIAL PRIMARY KEY,
    "task" VARCHAR(191) NOT NULL,
    "priority" VARCHAR(191) NOT NULL,
    "status" VARCHAR(191) NOT NULL,
    "term" TIMESTAMP(3) NOT NULL,
    "category" VARCHAR(191) NOT NULL,
    "description" VARCHAR(191) NOT NULL,
    "userId" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

-- AddForeignKey
ALTER TABLE "toDos" ADD CONSTRAINT "toDos_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
